const ACTIONS = {
	LOGIN: "LOGIN",
	GET_TOKEN: "GET_TOKEN",
	GET_USER: "GET_USER",
	GET_ALL_USERS: "GET_ALL_USERS",
	GET_ALL_MOVIES: "GET_ALL_MOVIES",
	GET_MOVIE: "GET_MOVIE",
};

export default ACTIONS;
